server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka6001:7001/eureka/,http://eureka6002:7002/eureka/
    fetch-registry: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    polling-interval-ms: 5000
