server:
  port: 8001
spring:
  application:
    name: payment-server-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001:7001/eureka/,http://eureka6002:7002/eureka/
